Repository gambitph/Stackable, pull requests merged in 2021-11, with the labels that each got.

#2001 Fix: Added transform in separator block
  src/block/separator/edit.js
  src/block/separator/schema.js
  src/block/separator/style.js
Labels: [block] Separator, Bug Fix

#2007 Feat: Dynamic Title in button block and other links
  src/block-components/helpers/link/edit.js
Labels: enhancement, PR: Needs Review, Dynamic Content, [block] Button, [block] Icon Button, [block] Social Buttons

#1993 Fix: Column widths x column gap in tablet and mobile
  src/block-components/advanced/style.js
  src/block-components/column/attributes.js
  src/block-components/column/style.js
  src/block-components/column/use-column.js
  src/block-components/column/util.js
  src/block-components/content-align/attributes.js
  src/block-components/content-align/edit.js
  src/block-components/content-align/style.js
  src/block/column/style.js
  src/block/columns/editor.scss
  src/block/columns/style.scss
  src/components/resizable-column/get-snap-widths.js
  src/components/resizable-column/index.js
  src/hooks/use-block-context.js
  src/hooks/use-block-hover-state.js
  src/plugins/design-library-button/design-library-button.js
  src/styles/block-transitions.scss
  src/styles/editor-block-transitions.scss
  src/util/index.js
  src/util/styles/index.js
  src/util/styles/style-object.js
Labels: PR: Good to Merge

#1994 Test: Changed Github Actions main branch
  .github/workflows/compressed-diff.yml
  .github/workflows/js-unit-test.yml
  .github/workflows/php-5.6.39.yml
  .github/workflows/php-7.3.5.yml
  .github/workflows/php-7.4.1.yml
  .github/workflows/php-8.0.0.yml
Labels: PR: Needs Review, Continuous Integration

#2017 Fix: Removed blocks caching for performance
  src/blocks.php
Labels: performance
