Repository gambitph/Stackable, pull requests merged in 2022-02, with the labels that each got.

#2140 Fix editor performance issues
  src/block/column/edit.js
  src/block/image-box/edit.js
  src/block/posts/edit.js
  src/components/base-control2/hooks.js
  src/components/base-control2/hover-state-toggle.js
  src/components/base-control2/index.js
  src/components/base-control2/reset-button.js
  src/components/button-icon-popover-control/index.js
  src/components/dynamic-content-control/index.js
  src/components/image-control2/index.js
  src/components/resizable-column/index.js
  src/components/resizable-column/use-device-editor-classes.js
  src/components/shadow-control/index.js
  src/format-types/highlight/index.js
  src/hooks/index.js
  src/hooks/use-block-context.js
  src/hooks/use-block-hover-state.js
  src/plugins/block-hover-state/index.js
  src/plugins/design-library-button/design-library-button.js
  src/plugins/get-editor-dom/index.js
  src/plugins/get-editor-dom/store.js
  src/plugins/index.js
Labels: performance

#2015 Feat: Block alignment support for heading block
  src/block/heading/index.js
Labels: enhancement, PR: Reviewed w/ Comments, PR: Needs Review, [block] Heading

#2147 Add slider for list gap.
  src/block/icon-list/edit.js
  src/block/icon-list/schema.js
  src/block/icon-list/style.js
Labels: PR: Needs Review

#2155 Accordion wont open in old browser
  .config/webpack.config.dev.js
  .config/webpack.config.prod.js
  src/block/accordion/frontend-accordion-polyfill.js
  src/block/accordion/index.php
Labels: PR: Needs Review

#2168 Added a class for featured images in post blocks so that margin bottom can be changed. Added styles so that line-height of title in posts blocks are now visible if <= 1.
  src/block/posts/style.js
  src/block/posts/style.scss
  src/block/posts/util.js
Labels: PR: Needs Review

#2165 Add inverted horizontal layout variation to posts block.
  src/block/posts/edit.js
  src/block/posts/images/horizontal-card-2.svg
  src/block/posts/util.js
  src/block/posts/variations.js
Labels: PR: Good to Merge
