Repository gambitph/Stackable, pull requests merged in 2022-08, with the labels that each got.

#2348 fix (size-and-spacing-control): exclude horizontal alignment on full-…
  src/block-components/helpers/size/style.js
Labels: PR: Good to Merge

#2368 fix: Removes highlight option from the button toolbar to prevent block errors.
  src/format-types/highlight/index.js
Labels: PR: Needs Review

#2240 Fix position sticky advanced bloc setting
  src/block-components/advanced/style.js
  src/block/column/editor.scss
  src/block/column/style.scss
Labels: [block] Column, [block] All Blocks

#2395 Feat (count-up): Control the speed of the count up animation
  src/block/count-up/edit.js
  src/block/count-up/frontend-count-up.js
  src/block/count-up/save.js
  src/block/count-up/schema.js
Labels: PR: Needs Review
