Repository gambitph/Stackable, pull requests merged in 2022-05, with the labels that each got.

#2263 Accordion will now open in Windows if "Show animations option in Windows" option is off.
  src/block/accordion/editor.scss
  src/block/accordion/style.scss
Labels: PR: Good to Merge, [block] Accordion

#2281 Prevents the column gap option from affecting inner blocks in the editor.
  src/block/columns/editor.scss
Labels: PR: Good to Merge

#2241 Add overflow: hidden to fix flicker.
  src/components/resizable-column/editor.scss
Labels: PR: Good to Merge, [block] Column

#2283 Container opacity and shadows can now be visible with colors from Blocksy color palette.
  src/block-components/button/edit.js
  src/block-components/helpers/backgrounds/style.js
  src/block-components/typography/edit.js
  src/components/shadow-control/index.js
  src/util/colors.js
  src/util/index.js
Labels: PR: Needs Review

#2282 Margin-bottom is 0 in icon list so that themes' CSS wont affect it.
  src/block/icon-list/style.scss
Labels: PR: Needs Review

#2294 Added margin to the left of the color indicator to prevent it from misaligning in the color palette.
  src/components/color-palette-control/editor.scss
Labels: PR: Needs Review

#2304 Added styles to fix the misaligned block styles component.
  src/block-components/block-style/block-styles.js
  src/block-components/block-style/editor.scss
Labels: PR: Needs Review, [block] Button, UI

#2306 Fix: removed paddings in toolbar stackable icons.
  src/format-types/highlight/editor.scss
Labels: PR: Needs Review
